package app

import "testing"

// These expectations were confirmed against the real docs/index.html
// generated by scripts/build_report.py before it was ported to Go -- they
// guard the byte-identical requirement the Go port was built to preserve.
func TestEncodeJSONEscapesNonASCII(t *testing.T) {
	got, err := encodeJSON(struct {
		Date  string `json:"date"`
		Label string `json:"label"`
	}{"2024-03-01", "Mar 2024: FID→INP"})
	if err != nil {
		t.Fatal(err)
	}
	want := `{"date": "2024-03-01", "label": "Mar 2024: FID\u2192INP"}`
	if got != want {
		t.Errorf("encodeJSON() = %q, want %q", got, want)
	}
}

func TestEncodeJSONSeparatorsAndOrder(t *testing.T) {
	got, err := encodeJSON(struct {
		A int   `json:"a"`
		B []int `json:"b"`
	}{1, []int{1, 2, 3}})
	if err != nil {
		t.Fatal(err)
	}
	want := `{"a": 1, "b": [1, 2, 3]}`
	if got != want {
		t.Errorf("encodeJSON() = %q, want %q", got, want)
	}
}

func TestFormatFloat(t *testing.T) {
	wants := map[float64]string{
		2.0:                "2.0",
		0.0:                "0.0",
		0.6341219649117935: "0.6341219649117935",
		100.0:              "100.0",
		0.0001:             "0.0001",
		1e21:               "1e+21",
		1e-5:               "1e-05",
	}
	for in, want := range wants {
		if got := formatFloat(in); got != want {
			t.Errorf("formatFloat(%v) = %q, want %q", in, got, want)
		}
	}
}
